"""add life records

Revision ID: 3a750f86e9c3
Revises: 5d11edea8c8f
Create Date: 2026-07-31 21:22:38.857586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3a750f86e9c3'
down_revision: Union[str, None] = '5d11edea8c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('life_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('goal_id', sa.String(length=36), nullable=False),
    sa.Column('record_type', sa.String(length=16), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('watermark_url', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('weather', sa.String(length=120), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('device_info', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['life_goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_life_records_goal_id'), 'life_records', ['goal_id'], unique=False)
    op.create_index(op.f('ix_life_records_user_id'), 'life_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_life_records_user_id'), table_name='life_records')
    op.drop_index(op.f('ix_life_records_goal_id'), table_name='life_records')
    op.drop_table('life_records')
    # ### end Alembic commands ###
