"""add user levels

Revision ID: 5d11edea8c8f
Revises: f660beab710f
Create Date: 2026-07-31 19:11:04.058361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5d11edea8c8f'
down_revision: Union[str, None] = 'f660beab710f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_levels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_levels_user')
    )
    op.create_index(op.f('ix_user_levels_user_id'), 'user_levels', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_levels_user_id'), table_name='user_levels')
    op.drop_table('user_levels')
    # ### end Alembic commands ###
