"""track growth plan task generation

Revision ID: 771fb65bcfdc
Revises: d0023f3b009c
Create Date: 2026-07-31 21:50:01.909590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '771fb65bcfdc'
down_revision: Union[str, None] = 'd0023f3b009c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'ai_content',
        sa.Column('task_generated', sa.Boolean(), nullable=False, server_default=sa.text('0')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_content', 'task_generated')
    # ### end Alembic commands ###
