"""add ai content

Revision ID: d0023f3b009c
Revises: 3a750f86e9c3
Create Date: 2026-07-31 21:39:20.345876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd0023f3b009c'
down_revision: Union[str, None] = '3a750f86e9c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_content',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_content_content_type'), 'ai_content', ['content_type'], unique=False)
    op.create_index(op.f('ix_ai_content_user_id'), 'ai_content', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_content_user_id'), table_name='ai_content')
    op.drop_index(op.f('ix_ai_content_content_type'), table_name='ai_content')
    op.drop_table('ai_content')
    # ### end Alembic commands ###
