"""add life goals

Revision ID: f1ae33da647c
Revises: d8b8ad15b6f7
Create Date: 2026-07-31 19:04:34.931842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f1ae33da647c'
down_revision: Union[str, None] = 'd8b8ad15b6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('life_goals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal_type', sa.String(length=16), nullable=False),
    sa.Column('difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('cover_image', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_life_goals_category'), 'life_goals', ['category'], unique=False)
    op.create_index(op.f('ix_life_goals_status'), 'life_goals', ['status'], unique=False)
    op.create_index(op.f('ix_life_goals_user_id'), 'life_goals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_life_goals_user_id'), table_name='life_goals')
    op.drop_index(op.f('ix_life_goals_status'), table_name='life_goals')
    op.drop_index(op.f('ix_life_goals_category'), table_name='life_goals')
    op.drop_table('life_goals')
    # ### end Alembic commands ###
