"""add life goal start date

Revision ID: f6d6e4edafc1
Revises: 771fb65bcfdc
Create Date: 2026-07-31 21:50:54.513694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f6d6e4edafc1'
down_revision: Union[str, None] = '771fb65bcfdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('life_goals', sa.Column('start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('life_goals', 'start_date')
    # ### end Alembic commands ###
