/**
 * API Client — fetch wrapper with cookie auth + SSE streaming.
 *
 * Consumes types auto-generated by openapi-typescript:
 *   pnpm run gen:types  →  lib/api/api.d.ts
 */
import type { paths } from "./api.d";

const API_BASE = process.env.NEXT_PUBLIC_API_BASE_URL ?? "/api/v1";

// ── Type helpers from generated OpenAPI types ────────────────
type ChatCompletionRequest =
  paths["/api/v1/chat/completions"]["post"]["requestBody"]["content"]["application/json"];

type ChatCompletionSyncResponse =
  paths["/api/v1/chat/completions/sync"]["post"]["responses"]["200"]["content"]["application/json"];

// ── Re-export for consumers ───────────────────────────────────
export type { ChatCompletionRequest, ChatCompletionSyncResponse };

// ── Base fetch with cookie auth ──────────────────────────────

async function apiFetch<T>(
  path: string,
  options: RequestInit = {},
): Promise<T> {
  const res = await fetch(`${API_BASE}${path}`, {
    ...options,
    credentials: "include",
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

  if (!res.ok) {
    const error = await res.json().catch(() => ({ message: res.statusText }));
    throw new Error(
      `API ${res.status}: ${error.message ?? error.detail ?? "Unknown error"}`,
    );
  }

  return res.json() as Promise<T>;
}

// ── SSE streaming fetch ──────────────────────────────────────

export interface SSEChunk {
  content: string;
  role?: string;
  finish_reason?: string | null;
}

/**
 * Stream a chat completion via Server-Sent Events.
 *
 * Calls POST /chat/completions and parses the SSE stream,
 * invoking `onChunk` for each incremental text delta.
 */
export async function streamChat(
  body: ChatCompletionRequest,
  onChunk: (chunk: SSEChunk) => void,
  onError?: (err: Error) => void,
): Promise<void> {
  const res = await fetch(`${API_BASE}/chat/completions`, {
    method: "POST",
    credentials: "include",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });

  if (!res.ok || !res.body) {
    const error = await res.json().catch(() => ({ message: res.statusText }));
    throw new Error(`API ${res.status}: ${error.message ?? "Stream failed"}`);
  }

  const reader = res.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";

  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;

      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split("\n");
      buffer = lines.pop() ?? "";

      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed.startsWith("data: ")) continue;

        const data = trimmed.slice(6);
        if (data === "[DONE]") return;

        try {
          const parsed = JSON.parse(data);
          const delta = parsed.choices?.[0]?.delta;
          if (delta) {
            onChunk({
              content: delta.content ?? "",
              role: delta.role,
              finish_reason: parsed.choices?.[0]?.finish_reason,
            });
          }
        } catch {
          // Skip malformed lines
        }
      }
    }
  } catch (err) {
    if (onError && err instanceof Error) {
      onError(err);
    } else {
      throw err;
    }
  }
}

// ── Non-streaming chat ──────────────────────────────────────

export async function sendChat(
  body: ChatCompletionRequest,
): Promise<ChatCompletionSyncResponse> {
  return apiFetch<ChatCompletionSyncResponse>("/chat/completions/sync", {
    method: "POST",
    body: JSON.stringify(body),
  });
}

// ── Generic typed request helpers ────────────────────────────

export const api = {
  get: <T>(path: string) => apiFetch<T>(path),
  post: <T>(path: string, body: unknown) =>
    apiFetch<T>(path, { method: "POST", body: JSON.stringify(body) }),
  put: <T>(path: string, body: unknown) =>
    apiFetch<T>(path, { method: "PUT", body: JSON.stringify(body) }),
  delete: <T>(path: string) =>
    apiFetch<T>(path, { method: "DELETE" }),
  stream: streamChat,
};
